## Importing numpy and creating an array

In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


## Quickly define special arrays

In [2]:
b = np.zeros((4,4),dtype=np.float)
print(b)
c = np.ones((4,3),dtype=np.int)
print(c)
d = np.eye(3,dtype=np.float)
print(d)
e = np.reshape(np.arange(10),(2,5))
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Array slicing

In [3]:
x = np.arange(10)
print(x)
x1 = x[2:8]
print(x1)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]


## Broadcasting

In [4]:
a = np.array([12,13,14])
print(a+3)
print(a.mean(),a.sum())

[15 16 17]
13.0 39


## Vectorization

In [5]:
a = np.arange(5)**3
print(np.sqrt(a))

[0.         1.         2.82842712 5.19615242 8.        ]


## Masking

In [10]:
a = np.random.rand(10).reshape((2,5))
b = np.logical_and((a>0.1),(a<0.5))
print(a)
print(b.sum())
print(a[np.logical_not(b)])

[[0.28136243 0.24431876 0.73340469 0.58548252 0.21224671]
 [0.33955263 0.07128523 0.89151886 0.44935812 0.6343237 ]]
5
[0.73340469 0.58548252 0.07128523 0.89151886 0.6343237 ]


## Challenge: Linear Algebra

In [ ]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
b = np.array([6,-4,27])
if np.linalg.det(A) == 0.0:
    print("No unique solution exists")
else:
    x = np.linalg.solve(A,b)
    print("Solution is: ",x)